version: '3.1'
services:
  app:
    container_name: persistenceteste
    image: persistenceteste
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_PASSWORD=netpacs123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres